id: opecha:P010731
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5560
  title: ས་སྐྱོང་འབུར་བའི་གདུང་རབས་ལས་འཕྲོས་པའི་འབྲོག་སྡེ་ཆེན་པོ་སྤོ་རོང་གི་བྱུང་བ་བརྗོད་པ་དྭངས་གསལ་མེ་ལོང་
  volume: ''
  author: ''
