id: I6811AE9F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:00:02+00:00'
last_modified: '2022-06-08T17:07:12.700509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5560
  title: ས་སྐྱོང་འབུར་བའི་གདུང་རབས་ལས་འཕྲོས་པའི་འབྲོག་སྡེ་ཆེན་པོ་སྤོ་རོང་གི་བྱུང་བ་བརྗོད་པ་དྭངས་གསལ་མེ་ལོང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    69C9:
      image_group_id: I1KG5628
      title: ''
      total_pages: 396
      order: 1
      base_file: 69C9.txt
    B2B1:
      image_group_id: I1KG5629
      title: ''
      total_pages: 208
      order: 2
      base_file: B2B1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
